# Generated by Django 5.2.12 on 2026-04-21 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaodeHabitos', '0002_tipoatividade_atividades_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atividades',
            unique_together={('usuario', 'nome_atividade')},
        ),
    ]
