# Generated by Django 5.2.12 on 2026-04-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestaodeHabitos', '0003_alter_atividades_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registro',
            unique_together={('atividade', 'data')},
        ),
    ]
