# Generated by Django 5.2.12 on 2026-05-26 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaodeHabitos', '0004_alter_registro_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('prova', 'Prova')], max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('multipla', 'Multipla Escolha'), ('aberta', 'Resposta Aberta')], max_length=10)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestaodeHabitos.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestaodeHabitos.questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestaodeHabitos.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestaodeHabitos.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
