# Generated by Django 5.2.12 on 2026-05-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestaodeHabitos', '0005_avaliacao_questao_alternativa_respostausuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
